branches:
  only:
  - master
  - release

dist: trusty
language: python
python:
  - '3.5'
matrix:
  include:
    ###############################################################################
    # Job #1 - SQF validation
    ###############################################################################
    - python: '3.5'
      before_script:
      - git clone https://github.com/jokoho48/sqf.git sqfLint
      script:
      - python3 tools/sqf_validator.py
      - python3 sqfLint/sqflint.py -d addons
    ###############################################################################
    # Job #2 - Building Extensions Disabled because not working :(
    ###############################################################################
    #- language: csharp
    #  before_install:
    #  - cd extensions
    #  - cd CLib
    #  solution: CLib.sln
