branches:
  only:
  - master
  - release

dist: trusty
language: python
python:
  - '3.6'
matrix:
  include:
    ###############################################################################
    # Job - SQF validation
    ###############################################################################
    - python: '3.6'
      before_script:
      - git clone https://github.com/jokoho48/sqf.git sqfLint
      script:
      - python3 tools/sqf_validator.py
      - python3 sqfLint/sqflint.py -d addons
